### ISSUE TITLE
Provide basic setup for dynamic type-based configurations

### ISSUE THREAD

**Issue by florianrusch-cluetec** [cluetec/lifeboat#10]
We aim to provide support for various resource types (such as sources and destinations), each requiring distinct configurations. Nevertheless, we strive to keep the setup process effortless. Therefore, our proposal is to specify the resource type and the associated configuration at the same level.

For example, the configuration should look something like the following:

```yaml
source:
  type: filesystem
  path: /take-my-backup-from-here

destination:
  type: filesystem
  path: /store-the-backup-here
```

The `type` field indicates the resource type (e.g. `filesystem`, `http`, `postgresql`, `mongodb`, `hashicorp vault`, ...). Everything else will be the configuration of the respective resource.
